chore(.eslintrc.json): remove consistent-return
w3c/spec-generator pull request #453
Opened 2021-07-19 00:45 UTC by marcoscaceres

Remove noisy rule... as our code show, there are valid cases for arrow functions that don't return anything.

2021-07-21 09:37 UTC, jennyliang220 requested changes
The airbnb code style is having "consistent-return":"error" for default. I don't have a strong opinion to change this rule. but if you were disabling it, the config should be:
```
"consistent-return":"off"
```
And the lint check should pass.

2021-07-26 04:02 UTC, jennyliang220 commented on .eslintrc.json
> +        "consistent-return": "off"
```suggestion
        "consistent-return": "off"
```

2021-07-26 04:07 UTC, jennyliang220 approved these changes

2021-07-26 04:07 UTC, merged

2021-07-26 04:14 UTC, marcoscaceres commented
Thanks @jennyliang220!